# Generated by Django 3.0.6 on 2020-06-02 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('shortname', models.CharField(max_length=5, null=True)),
                ('period', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Language', [('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada')])], max_length=200, null=True)),
                ('level', models.CharField(choices=[('Primary', 'Primary (1-4)'), ('Middle', 'Middle (5-7)'), ('High School', 'High School(8-10)')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('f_name', models.CharField(max_length=200, null=True)),
                ('l_name', models.CharField(max_length=200, null=True)),
                ('m_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('Administration', 'Administration'), ('IT', 'IT'), ('Maintainance & Support', 'Maintainance & Support'), ('Academics', [('Maths', 'Maths'), ('Science', 'Science'), ('Social Studies', 'Social Studies')])], max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('f_name', models.CharField(max_length=200, null=True)),
                ('l_name', models.CharField(max_length=200, null=True)),
                ('m_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grad_date', models.DateField()),
                ('coy', models.DateField()),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], max_length=200, null=True)),
                ('dob', models.DateField()),
                ('parent_details', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
