# Generated by Django 3.0.6 on 2020-06-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20200602_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
