# Generated by Django 3.0.6 on 2020-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20200602_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, default='index.png', null=True, upload_to=''),
        ),
    ]
