# Generated by Django 3.0.6 on 2020-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_auto_20200602_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
